In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/home/anaconda/Documents/Social_Network_Ads.csv')

In [4]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB

In [7]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [9]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [10]:
x = df.iloc[:,[2,3]].values

In [11]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000]])

In [12]:
y = df.iloc[:,4].values

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1])

In [20]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size = 0.25,random_state=42)

In [22]:
x_train

array([[    57, 122000],
       [    39,  71000],
       [    47,  25000],
       [    24,  19000],
       [    36,  50000],
       [    32, 150000],
       [    48,  29000],
       [    30, 107000],
       [    60,  34000],
       [    38,  61000],
       [    33,  31000],
       [    39,  71000],
       [    55,  39000],
       [    49,  39000],
       [    43, 112000],
       [    27,  20000],
       [    26,  17000],
       [    37,  93000],
       [    42,  54000],
       [    35,  61000],
       [    29,  75000],
       [    38,  80000],
       [    45,  26000],
       [    54, 108000],
       [    46,  23000],
       [    23,  28000],
       [    37,  75000],
       [    42,  65000],
       [    35,  71000],
       [    51, 146000],
       [    39,  96000],
       [    24,  89000],
       [    58,  95000],
       [    25,  22000],
       [    41,  59000],
       [    28,  89000],
       [    42,  80000],
       [    42, 108000],
       [    46,  96000],
       [    47, 113000],
       [    33,  28000],
       [    19,  25000],
       [    49,  89000],
       [    31,  15000],
       [    30,  79000],
       [    48, 141000],
       [    32, 117000],
       [    37,  71000],
       [    18,  86000],
       [    42,  79000],
       [    27,  84000],
       [    40,  65000],
       [    57,  74000],
       [    26,  15000],
       [    26,  80000],
       [    29,  43000],
       [    33, 149000],
       [    39,  42000],
       [    54, 104000],
       [    36,  33000],
       [    46,  32000],
       [    40, 142000],
       [    37,  62000],
       [    29, 148000],
       [    37,  57000],
       [    35,  50000],
       [    42,  53000],
       [    35,  38000],
       [    41,  30000],
       [    40,  72000],
       [    26,  15000],
       [    31,  68000],
       [    35,  53000],
       [    35,  25000],
       [    30,  89000],
       [    41,  72000],
       [    28, 123000],
       [    46,  82000],
       [    22,  63000],
       [    45,  22000],
       [    30,  49000],
       [    34,  25000],
       [    40,  75000],
       [    32, 117000],
       [    23,  82000],
       [    26,  80000],
       [    48, 131000],
       [    59, 143000],
       [    35,  55000],
       [    34,  43000],
       [    39,  61000],
       [    27,  96000],
       [    60,  83000],
       [    24,  55000],
       [    58, 144000],
       [    53, 104000],
       [    35,  79000],
       [    36,  99000],
       [    57,  60000],
       [    37, 137000],
       [    33,  43000],
       [    41,  71000],
       [    52,  21000],
       [    52, 150000],
       [    37,  70000],
       [    26,  84000],
       [    26,  72000],
       [    26,  52000],
       [    41,  60000],
       [    31,  66000],
       [    37, 144000],
       [    38,  61000],
       [    31,  34000],
       [    42,  75000],
       [    46, 117000],
       [    36,  52000],
       [    38,  71000],
       [    49,  88000],
       [    57,  33000],
       [    48, 138000],
       [    47,  50000],
       [    33,  69000],
       [    37, 146000],
       [    20,  82000],
       [    40,  47000],
       [    35,  22000],
       [    20,  36000],
       [    45,  45000],
       [    26,  43000],
       [    58, 101000],
       [    40,  57000],
       [    38, 112000],
       [    37,  80000],
       [    49,  28000],
       [    36,  75000],
       [    41,  72000],
       [    35,  60000],
       [    43, 129000],
       [    41,  87000],
       [    38, 113000],
       [    58,  23000],
       [    26,  32000],
       [    32,  18000],
       [    41,  52000],
       [    31,  18000],
       [    35,  88000],
       [    48,  35000],
       [    27,  89000],
       [    35,  97000],
       [    42,  73000],
       [    21,  68000],
       [    41,  72000],
       [    33,  60000],
       [    39, 134000],
       [    28,  84000],
       [    46,  88000],
       [    24,  58000],
       [    31, 118000],
       [    50,  88000],
       [    20,  82000],
       [    32, 135000],
       [    20,  86000],
       [    35,  27000],
       [    29,  43000],
       [    21,  88000],
       [    35,  59000],
       [    45,  32000],
       [    60,  42000],
       [    35,  91000],
       [    35,  44000],
       [    18,  44000],
       [    42, 149000],
       [    45,  79000],
       [    40,  60000],
       [    24,  23000],
       [    33,  51000],
       [    42,  70000],
       [    55, 130000],
       [    50,  44000],
       [    48, 119000],
       [    19,  76000],
       [    41,  72000],
       [    40,  71000],
       [    27,  88000],
       [    36, 126000],
       [    35,  75000],
       [    35,  58000],
       [    34, 115000],
       [    35,  73000],
       [    60, 108000],
       [    25,  87000],
       [    27,  54000],
       [    21,  16000],
       [    37,  74000],
       [    35,  39000],
       [    54,  70000],
       [    47,  30000],
       [    38,  50000],
       [    35, 147000],
       [    35,  77000],
       [    41,  79000],
       [    37,  33000],
       [    60,  46000],
       [    28,  59000],
       [    23,  66000],
       [    23,  63000],
       [    30,  17000],
       [    25,  33000],
       [    59,  83000],
       [    58,  38000],
       [    18,  82000],
       [    46,  59000],
       [    27,  17000],
       [    58,  47000],
       [    48,  30000],
       [    49,  65000],
       [    50,  36000],
       [    53,  72000],
       [    40,  57000],
       [    52, 114000],
       [    59,  42000],
       [    36,  63000],
       [    42, 104000],
       [    37,  52000],
       [    48,  33000],
       [    59,  29000],
       [    37,  79000],
       [    40,  61000],
       [    49,  74000],
       [    25,  90000],
       [    30,  15000],
       [    40,  78000],
       [    24,  84000],
       [    38,  50000],
       [    45, 131000],
       [    21,  72000],
       [    35,  23000],
       [    35,  20000],
       [    31,  89000],
       [    30,  80000],
       [    47,  47000],
       [    27,  90000],
       [    35,  72000],
       [    30, 116000],
       [    39, 122000],
       [    29,  83000],
       [    41,  63000],
       [    48,  90000],
       [    38,  59000],
       [    32,  18000],
       [    39,  75000],
       [    26,  81000],
       [    39, 106000],
       [    22,  55000],
       [    36, 118000],
       [    60,  42000],
       [    28,  55000],
       [    51, 134000],
       [    49,  28000],
       [    36,  60000],
       [    56, 104000],
       [    27,  58000],
       [    24,  32000],
       [    34,  72000],
       [    28,  32000],
       [    50,  20000],
       [    33,  41000],
       [    29,  47000],
       [    22,  18000],
       [    30, 135000],
       [    47, 105000],
       [    46,  79000],
       [    48, 134000],
       [    47,  49000],
       [    49, 141000],
       [    32, 100000],
       [    38,  71000],
       [    19,  26000],
       [    37,  77000],
       [    47,  51000],
       [    40,  57000],
       [    36, 125000],
       [    20,  74000],
       [    31,  58000],
       [    41,  45000],
       [    42,  54000],
       [    28,  37000],
       [    39,  73000],
       [    28,  85000],
       [    38,  51000],
       [    47,  43000],
       [    37,  72000],
       [    49,  36000],
       [    45,  22000],
       [    35,  72000],
       [    24,  27000],
       [    26,  35000],
       [    43, 133000],
       [    39,  77000],
       [    32,  86000]])

In [23]:
x_train.shape

(300, 2)

In [24]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [25]:
y_train.shape

(300,)

In [26]:
x_test

array([[    46,  22000],
       [    59,  88000],
       [    28,  44000],
       [    48,  96000],
       [    29,  28000],
       [    30,  62000],
       [    47, 107000],
       [    29,  83000],
       [    40,  75000],
       [    42,  65000],
       [    35,  65000],
       [    53,  34000],
       [    23,  48000],
       [    20,  23000],
       [    30,  87000],
       [    35, 108000],
       [    52,  38000],
       [    46,  74000],
       [    39,  42000],
       [    56,  60000],
       [    22,  27000],
       [    29,  80000],
       [    47,  23000],
       [    59,  76000],
       [    19,  19000],
       [    51,  23000],
       [    42,  80000],
       [    37,  53000],
       [    55, 125000],
       [    19,  21000],
       [    46,  41000],
       [    19,  70000],
       [    36, 144000],
       [    28,  79000],
       [    40, 107000],
       [    35,  75000],
       [    37,  55000],
       [    38,  65000],
       [    26,  30000],
       [    18,  68000],
       [    48,  33000],
       [    24,  55000],
       [    18,  52000],
       [    47,  20000],
       [    20,  49000],
       [    44, 139000],
       [    29,  61000],
       [    31,  71000],
       [    48,  41000],
       [    34,  43000],
       [    25,  79000],
       [    53,  82000],
       [    38,  55000],
       [    25,  80000],
       [    37,  80000],
       [    27,  31000],
       [    60, 102000],
       [    26, 118000],
       [    31,  74000],
       [    31,  76000],
       [    41,  51000],
       [    35,  57000],
       [    52,  90000],
       [    28,  87000],
       [    28,  59000],
       [    27, 137000],
       [    42,  90000],
       [    47, 144000],
       [    39,  59000],
       [    33, 113000],
       [    52, 138000],
       [    19,  85000],
       [    27,  58000],
       [    23,  20000],
       [    47,  34000],
       [    35,  50000],
       [    56, 133000],
       [    54,  26000],
       [    35,  47000],
       [    37,  78000],
       [    27,  57000],
       [    46,  28000],
       [    39, 134000],
       [    44,  39000],
       [    57,  26000],
       [    32, 120000],
       [    41,  52000],
       [    48,  74000],
       [    26,  86000],
       [    22,  81000],
       [    49,  86000],
       [    36,  54000],
       [    40,  59000],
       [    41,  80000],
       [    26,  16000],
       [    39,  79000],
       [    59, 130000],
       [    42,  64000],
       [    53, 143000],
       [    34, 112000]])

In [27]:
x_test.shape

(100, 2)

In [28]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [29]:
y_test.shape

(100,)

In [34]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

/home/anaconda/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [35]:
x_train

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255],
       [ 1.0088136 , -1.19473064],
       [-0.75873781,  1.08372877],
       [ 2.1871812 , -1.04867555],
       [ 0.0268406 , -0.25997806],
       [-0.46414591, -1.1363086 ],
       [ 0.1250379 ,  0.03213212],
       [ 1.6961947 , -0.90262046],
       [ 1.1070109 , -0.90262046],
       [ 0.5178271 ,  1.22978386],
       [-1.05332971, -1.4576298 ],
       [-1.15152701, -1.54526286],
       [-0.0713567 ,  0.67477452],
       [ 0.4196298 , -0.46445519],
       [-0.2677513 , -0.25997806],
       [-0.85693511,  0.14897619],
       [ 0.0268406 ,  0.29503128],
       [ 0.7142217 , -1.28236369],
       [ 1.5979974 ,  1.11293979],
       [ 0.812419  , -1.36999675],
       [-1.44611891, -1.22394166],
       [-0.0713567 ,  0.14897619],
       [ 0.4196298 , -0.14313399],
       [-0.2677513 ,  0.03213212],
       [ 1.3034055 ,  2.22295848],
       [ 0.1250379 ,  0.76240757],
       [-1.34792161,  0.55793045],
       [ 1.9907866 ,  0.73319655],
       [-1.24972431, -1.39920777],
       [ 0.3214325 , -0.3184001 ],
       [-0.95513241,  0.55793045],
       [ 0.4196298 ,  0.29503128],
       [ 0.4196298 ,  1.11293979],
       [ 0.812419  ,  0.76240757],
       [ 0.9106163 ,  1.25899488],
       [-0.46414591, -1.22394166],
       [-1.83890811, -1.31157471],
       [ 1.1070109 ,  0.55793045],
       [-0.66054051, -1.60368489],
       [-0.75873781,  0.26582026],
       [ 1.0088136 ,  2.07690339],
       [-0.56234321,  1.37583895],
       [-0.0713567 ,  0.03213212],
       [-1.93710541,  0.47029739],
       [ 0.4196298 ,  0.26582026],
       [-1.05332971,  0.41187535],
       [ 0.2232352 , -0.14313399],
       [ 1.8925893 ,  0.11976517],
       [-1.15152701, -1.60368489],
       [-1.15152701,  0.29503128],
       [-0.85693511, -0.78577639],
       [-0.46414591,  2.31059153],
       [ 0.1250379 , -0.8149874 ],
       [ 1.5979974 ,  0.99609572],
       [-0.169554  , -1.07788657],
       [ 0.812419  , -1.10709759],
       [ 0.2232352 ,  2.1061144 ],
       [-0.0713567 , -0.23076704],
       [-0.85693511,  2.28138051],
       [-0.0713567 , -0.37682213],
       [-0.2677513 , -0.58129926],
       [ 0.4196298 , -0.49366621],
       [-0.2677513 , -0.93183148],
       [ 0.3214325 , -1.16551962],
       [ 0.2232352 ,  0.06134314],
       [-1.15152701, -1.60368489],
       [-0.66054051, -0.05550093],
       [-0.2677513 , -0.49366621],
       [-0.2677513 , -1.31157471],
       [-0.75873781,  0.55793045],
       [ 0.3214325 ,  0.06134314],
       [-0.95513241,  1.55110506],
       [ 0.812419  ,  0.35345332],
       [-1.54431621, -0.20155602],
       [ 0.7142217 , -1.39920777],
       [-0.75873781, -0.61051028],
       [-0.36594861, -1.31157471],
       [ 0.2232352 ,  0.14897619],
       [-0.56234321,  1.37583895],
       [-1.44611891,  0.35345332],
       [-1.15152701,  0.29503128],
       [ 1.0088136 ,  1.7847932 ],
       [ 2.0889839 ,  2.13532542],
       [-0.2677513 , -0.43524417],
       [-0.36594861, -0.78577639],
       [ 0.1250379 , -0.25997806],
       [-1.05332971,  0.76240757],
       [ 2.1871812 ,  0.38266434],
       [-1.34792161, -0.43524417],
       [ 1.9907866 ,  2.16453644],
       [ 1.4998001 ,  0.99609572],
       [-0.2677513 ,  0.26582026],
       [-0.169554  ,  0.85004063],
       [ 1.8925893 , -0.28918908],
       [-0.0713567 ,  1.96005931],
       [-0.46414591, -0.78577639],
       [ 0.3214325 ,  0.03213212],
       [ 1.4016028 , -1.42841878],
       [ 1.4016028 ,  2.33980255],
       [-0.0713567 ,  0.0029211 ],
       [-1.15152701,  0.41187535],
       [-1.15152701,  0.06134314],
       [-1.15152701, -0.52287722],
       [ 0.3214325 , -0.28918908],
       [-0.66054051, -0.11392297],
       [-0.0713567 ,  2.16453644],
       [ 0.0268406 , -0.25997806],
       [-0.66054051, -1.04867555],
       [ 0.4196298 ,  0.14897619],
       [ 0.812419  ,  1.37583895],
       [-0.169554  , -0.52287722],
       [ 0.0268406 ,  0.03213212],
       [ 1.1070109 ,  0.52871943],
       [ 1.8925893 , -1.07788657],
       [ 1.0088136 ,  1.98927033],
       [ 0.9106163 , -0.58129926],
       [-0.46414591, -0.02628992],
       [-0.0713567 ,  2.22295848],
       [-1.74071081,  0.35345332],
       [ 0.2232352 , -0.66893231],
       [-0.2677513 , -1.39920777],
       [-1.74071081, -0.99025351],
       [ 0.7142217 , -0.72735435],
       [-1.15152701, -0.78577639],
       [ 1.9907866 ,  0.90846266],
       [ 0.2232352 , -0.37682213],
       [ 0.0268406 ,  1.22978386],
       [-0.0713567 ,  0.29503128],
       [ 1.1070109 , -1.22394166],
       [-0.169554  ,  0.14897619],
       [ 0.3214325 ,  0.06134314],
       [-0.2677513 , -0.28918908],
       [ 0.5178271 ,  1.72637117],
       [ 0.3214325 ,  0.49950841],
       [ 0.0268406 ,  1.25899488],
       [ 1.9907866 , -1.36999675],
       [-1.15152701, -1.10709759],
       [-0.56234321, -1.51605184],
       [ 0.3214325 , -0.52287722],
       [-0.66054051, -1.51605184],
       [-0.2677513 ,  0.52871943],
       [ 1.0088136 , -1.01946453],
       [-1.05332971,  0.55793045],
       [-0.2677513 ,  0.79161859],
       [ 0.4196298 ,  0.09055416],
       [-1.64251351, -0.05550093],
       [ 0.3214325 ,  0.06134314],
       [-0.46414591, -0.28918908],
       [ 0.1250379 ,  1.87242626],
       [-0.95513241,  0.41187535],
       [ 0.812419  ,  0.52871943],
       [-1.34792161, -0.34761112],
       [-0.66054051,  1.40504997],
       [ 1.2052082 ,  0.52871943],
       [-1.74071081,  0.35345332],
       [-0.56234321,  1.90163728],
       [-1.74071081,  0.47029739],
       [-0.2677513 , -1.25315268],
       [-0.85693511, -0.78577639],
       [-1.64251351,  0.52871943],
       [-0.2677513 , -0.3184001 ],
       [ 0.7142217 , -1.10709759],
       [ 2.1871812 , -0.8149874 ],
       [-0.2677513 ,  0.61635248],
       [-0.2677513 , -0.75656537],
       [-1.93710541, -0.75656537],
       [ 0.4196298 ,  2.31059153],
       [ 0.7142217 ,  0.26582026],
       [ 0.2232352 , -0.28918908],
       [-1.34792161, -1.36999675],
       [-0.46414591, -0.55208824],
       [ 0.4196298 ,  0.0029211 ],
       [ 1.6961947 ,  1.75558219],
       [ 1.2052082 , -0.75656537],
       [ 1.0088136 ,  1.43426099],
       [-1.83890811,  0.17818721],
       [ 0.3214325 ,  0.06134314],
       [ 0.2232352 ,  0.03213212],
       [-1.05332971,  0.52871943],
       [-0.169554  ,  1.63873811],
       [-0.2677513 ,  0.14897619],
       [-0.2677513 , -0.34761112],
       [-0.36594861,  1.31741692],
       [-0.2677513 ,  0.09055416],
       [ 2.1871812 ,  1.11293979],
       [-1.24972431,  0.49950841],
       [-1.05332971, -0.46445519],
       [-1.64251351, -1.57447387],
       [-0.0713567 ,  0.11976517],
       [-0.2677513 , -0.90262046],
       [ 1.5979974 ,  0.0029211 ],
       [ 0.9106163 , -1.16551962],
       [ 0.0268406 , -0.58129926],
       [-0.2677513 ,  2.25216949],
       [-0.2677513 ,  0.20739823],
       [ 0.3214325 ,  0.26582026],
       [-0.0713567 , -1.07788657],
       [ 2.1871812 , -0.69814333],
       [-0.95513241, -0.3184001 ],
       [-1.44611891, -0.11392297],
       [-1.44611891, -0.20155602],
       [-0.75873781, -1.54526286],
       [-1.24972431, -1.07788657],
       [ 2.0889839 ,  0.38266434],
       [ 1.9907866 , -0.93183148],
       [-1.93710541,  0.35345332],
       [ 0.812419  , -0.3184001 ],
       [-1.05332971, -1.54526286],
       [ 1.9907866 , -0.66893231],
       [ 1.0088136 , -1.16551962],
       [ 1.1070109 , -0.14313399],
       [ 1.2052082 , -0.99025351],
       [ 1.4998001 ,  0.06134314],
       [ 0.2232352 , -0.37682213],
       [ 1.4016028 ,  1.2882059 ],
       [ 2.0889839 , -0.8149874 ],
       [-0.169554  , -0.20155602],
       [ 0.4196298 ,  0.99609572],
       [-0.0713567 , -0.52287722],
       [ 1.0088136 , -1.07788657],
       [ 2.0889839 , -1.19473064],
       [-0.0713567 ,  0.26582026],
       [ 0.2232352 , -0.25997806],
       [ 1.1070109 ,  0.11976517],
       [-1.24972431,  0.58714146],
       [-0.75873781, -1.60368489],
       [ 0.2232352 ,  0.23660925],
       [-1.34792161,  0.41187535],
       [ 0.0268406 , -0.58129926],
       [ 0.7142217 ,  1.7847932 ],
       [-1.64251351,  0.06134314],
       [-0.2677513 , -1.36999675],
       [-0.2677513 , -1.4576298 ],
       [-0.66054051,  0.55793045],
       [-0.75873781,  0.29503128],
       [ 0.9106163 , -0.66893231],
       [-1.05332971,  0.58714146],
       [-0.2677513 ,  0.06134314],
       [-0.75873781,  1.34662793],
       [ 0.1250379 ,  1.52189404],
       [-0.85693511,  0.38266434],
       [ 0.3214325 , -0.20155602],
       [ 1.0088136 ,  0.58714146],
       [ 0.0268406 , -0.3184001 ],
       [-0.56234321, -1.51605184],
       [ 0.1250379 ,  0.14897619],
       [-1.15152701,  0.3242423 ],
       [ 0.1250379 ,  1.05451775],
       [-1.54431621, -0.43524417],
       [-0.169554  ,  1.40504997],
       [ 2.1871812 , -0.8149874 ],
       [-0.95513241, -0.43524417],
       [ 1.3034055 ,  1.87242626],
       [ 1.1070109 , -1.22394166],
       [-0.169554  , -0.28918908],
       [ 1.794392  ,  0.99609572],
       [-1.05332971, -0.34761112],
       [-1.34792161, -1.10709759],
       [-0.36594861,  0.06134314],
       [-0.95513241, -1.10709759],
       [ 1.2052082 , -1.4576298 ],
       [-0.46414591, -0.84419842],
       [-0.85693511, -0.66893231],
       [-1.54431621, -1.51605184],
       [-0.75873781,  1.90163728],
       [ 0.9106163 ,  1.02530673],
       [ 0.812419  ,  0.26582026],
       [ 1.0088136 ,  1.87242626],
       [ 0.9106163 , -0.61051028],
       [ 1.1070109 ,  2.07690339],
       [-0.56234321,  0.87925164],
       [ 0.0268406 ,  0.03213212],
       [-1.83890811, -1.28236369],
       [-0.0713567 ,  0.20739823],
       [ 0.9106163 , -0.55208824],
       [ 0.2232352 , -0.37682213],
       [-0.169554  ,  1.6095271 ],
       [-1.74071081,  0.11976517],
       [-0.66054051, -0.34761112],
       [ 0.3214325 , -0.72735435],
       [ 0.4196298 , -0.46445519],
       [-0.95513241, -0.96104249],
       [ 0.1250379 ,  0.09055416],
       [-0.95513241,  0.44108637],
       [ 0.0268406 , -0.55208824],
       [ 0.9106163 , -0.78577639],
       [-0.0713567 ,  0.06134314],
       [ 1.1070109 , -0.99025351],
       [ 0.7142217 , -1.39920777],
       [-0.2677513 ,  0.06134314],
       [-1.34792161, -1.25315268],
       [-1.15152701, -1.01946453],
       [ 0.5178271 ,  1.84321524],
       [ 0.1250379 ,  0.20739823],
       [-0.56234321,  0.47029739]])

In [36]:
x_test

array([[ 0.75872215, -1.41078892],
       [ 1.9109871 ,  0.5590031 ],
       [-0.83672162, -0.75419158],
       [ 0.93599368,  0.79776576],
       [-0.74808586, -1.23171691],
       [-0.65945009, -0.21697557],
       [ 0.84735791,  1.12606443],
       [-0.74808586,  0.40977643],
       [ 0.22690756,  0.17101376],
       [ 0.40417909, -0.12743957],
       [-0.21627127, -0.12743957],
       [ 1.37917251, -1.05264491],
       [-1.27990045, -0.63481024],
       [-1.54580774, -1.38094358],
       [-0.65945009,  0.52915776],
       [-0.21627127,  1.15590977],
       [ 1.29053674, -0.93326358],
       [ 0.75872215,  0.14116843],
       [ 0.13827179, -0.81388224],
       [ 1.6450798 , -0.27666624],
       [-1.36853621, -1.26156225],
       [-0.74808586,  0.32024043],
       [ 0.84735791, -1.38094358],
       [ 1.9109871 ,  0.20085909],
       [-1.63444351, -1.50032492],
       [ 1.20190098, -1.38094358],
       [ 0.40417909,  0.32024043],
       [-0.03899974, -0.48558358],
       [ 1.55644404,  1.66328044],
       [-1.63444351, -1.44063425],
       [ 0.75872215, -0.84372758],
       [-1.63444351,  0.02178709],
       [-0.1276355 ,  2.23034177],
       [-0.83672162,  0.2903951 ],
       [ 0.22690756,  1.12606443],
       [-0.21627127,  0.17101376],
       [-0.03899974, -0.42589291],
       [ 0.04963603, -0.12743957],
       [-1.01399315, -1.17202625],
       [-1.72307927, -0.03790357],
       [ 0.93599368, -1.08249025],
       [-1.19126468, -0.42589291],
       [-1.72307927, -0.51542891],
       [ 0.84735791, -1.47047958],
       [-1.54580774, -0.60496491],
       [ 0.58145062,  2.08111511],
       [-0.74808586, -0.24682091],
       [-0.57081433,  0.05163243],
       [ 0.93599368, -0.84372758],
       [-0.30490703, -0.78403691],
       [-1.10262892,  0.2903951 ],
       [ 1.37917251,  0.3799311 ],
       [ 0.04963603, -0.42589291],
       [-1.10262892,  0.32024043],
       [-0.03899974,  0.32024043],
       [-0.92535739, -1.14218091],
       [ 1.99962286,  0.97683777],
       [-1.01399315,  1.4543631 ],
       [-0.57081433,  0.14116843],
       [-0.57081433,  0.20085909],
       [ 0.31554332, -0.54527424],
       [-0.21627127, -0.36620224],
       [ 1.29053674,  0.61869376],
       [-0.83672162,  0.52915776],
       [-0.83672162, -0.30651158],
       [-0.92535739,  2.02142444],
       [ 0.40417909,  0.61869376],
       [ 0.84735791,  2.23034177],
       [ 0.13827179, -0.30651158],
       [-0.3935428 ,  1.30513643],
       [ 1.29053674,  2.05126977],
       [-1.63444351,  0.4694671 ],
       [-0.92535739, -0.33635691],
       [-1.27990045, -1.47047958],
       [ 0.84735791, -1.05264491],
       [-0.21627127, -0.57511958],
       [ 1.6450798 ,  1.9020431 ],
       [ 1.46780827, -1.29140758],
       [-0.21627127, -0.66465558],
       [-0.03899974,  0.26054976],
       [-0.92535739, -0.36620224],
       [ 0.75872215, -1.23171691],
       [ 0.13827179,  1.93188844],
       [ 0.58145062, -0.90341825],
       [ 1.73371557, -1.29140758],
       [-0.48217856,  1.51405377],
       [ 0.31554332, -0.51542891],
       [ 0.93599368,  0.14116843],
       [-1.01399315,  0.49931243],
       [-1.36853621,  0.35008576],
       [ 1.02462945,  0.49931243],
       [-0.1276355 , -0.45573824],
       [ 0.22690756, -0.30651158],
       [ 0.31554332,  0.32024043],
       [-1.01399315, -1.58986092],
       [ 0.13827179,  0.2903951 ],
       [ 1.9109871 ,  1.8125071 ],
       [ 0.40417909, -0.15728491],
       [ 1.37917251,  2.20049644],
       [-0.30490703,  1.2752911 ]])

In [37]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state = 0)
classifier.fit (x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [39]:
y_pred= classifier.predict(x_test)

In [40]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [41]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [44]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[61,  2],
       [12, 25]])

In [45]:
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)* 100
accuracy

86.0

In [46]:
tp=cm[0,[0]]
print('True Positive :',tp)

True Positive : [61]

In [48]:
fp=cm[0,[1]]
print('False Positive :', fp)

False Positive : [2]

In [49]:
fn=cm[1,[0]]
print('False Negative :', fn)

False Negative : [12]

In [50]:
tn=cm[1,[1]]
print('True Negative :', tn)

True Negative : [25]

In [51]:
accuracy_cm =((tp+tn)/(tp+fp+fn+tn))
print('Accuracy :',accuracy_cm*100)

Accuracy : [86.]

In [52]:
error_rate_cm =((fp+fn)/(tp+fp+fn+tn))
print('Error Rate :',error_rate_cm*100)

Error Rate : [14.]

In [53]:
precision_cm =(tp/(tp + fp))
print('precision :',precision_cm*100)

precision : [96.82539683]

In [54]:
recall_cm=(tp/(tp+fn))
print('sensitivity:', recall_cm*100)

sensitivity: [83.56164384]

In [55]:
specificity_cm = (tn/(tn+fp))
print('Specificity:',specificity_cm*100)

Specificity: [92.59259259]